// Generated by gencpp from file sbg_driver/SbgMag.msg
// DO NOT EDIT!


#ifndef SBG_DRIVER_MESSAGE_SBGMAG_H
#define SBG_DRIVER_MESSAGE_SBGMAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <sbg_driver/SbgMagStatus.h>

namespace sbg_driver
{
template <class ContainerAllocator>
struct SbgMag_
{
  typedef SbgMag_<ContainerAllocator> Type;

  SbgMag_()
    : header()
    , time_stamp(0)
    , mag()
    , accel()
    , status()  {
    }
  SbgMag_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_stamp(0)
    , mag(_alloc)
    , accel(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _mag_type;
  _mag_type mag;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accel_type;
  _accel_type accel;

   typedef  ::sbg_driver::SbgMagStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::sbg_driver::SbgMag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sbg_driver::SbgMag_<ContainerAllocator> const> ConstPtr;

}; // struct SbgMag_

typedef ::sbg_driver::SbgMag_<std::allocator<void> > SbgMag;

typedef boost::shared_ptr< ::sbg_driver::SbgMag > SbgMagPtr;
typedef boost::shared_ptr< ::sbg_driver::SbgMag const> SbgMagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sbg_driver::SbgMag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sbg_driver::SbgMag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sbg_driver::SbgMag_<ContainerAllocator1> & lhs, const ::sbg_driver::SbgMag_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time_stamp == rhs.time_stamp &&
    lhs.mag == rhs.mag &&
    lhs.accel == rhs.accel &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sbg_driver::SbgMag_<ContainerAllocator1> & lhs, const ::sbg_driver::SbgMag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sbg_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sbg_driver::SbgMag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sbg_driver::SbgMag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sbg_driver::SbgMag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sbg_driver::SbgMag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sbg_driver::SbgMag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sbg_driver::SbgMag_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sbg_driver::SbgMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de7614c4cbb6cbd430c4a9b79bad88ca";
  }

  static const char* value(const ::sbg_driver::SbgMag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde7614c4cbb6cbd4ULL;
  static const uint64_t static_value2 = 0x30c4a9b79bad88caULL;
};

template<class ContainerAllocator>
struct DataType< ::sbg_driver::SbgMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sbg_driver/SbgMag";
  }

  static const char* value(const ::sbg_driver::SbgMag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sbg_driver::SbgMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SBG Ellipse Messages\n"
"Header header\n"
"\n"
"# Time since sensor is powered up (us)\n"
"uint32 time_stamp\n"
"\n"
"# Magnetometer output (X, Y, Z)\n"
"geometry_msgs/Vector3 mag\n"
"\n"
"# Accelerometer output (X, Y, Z) in m/s2\n"
"geometry_msgs/Vector3 accel\n"
"\n"
"# Status\n"
"SbgMagStatus status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: sbg_driver/SbgMagStatus\n"
"# SBG Ellipse Messages\n"
"# Submessage\n"
"\n"
"# True if the magnetometer X has passed the self test.\n"
"bool mag_x\n"
"\n"
"# True if the magnetometer Y has passed the self test.\n"
"bool mag_y\n"
"\n"
"# True if the magnetometer Z has passed the self test.\n"
"bool mag_z\n"
"\n"
"# True if the accelerometer X has passed the self test.\n"
"bool accel_x\n"
"\n"
"# True if the accelerometer Y has passed the self test.\n"
"bool accel_y\n"
"\n"
"# True if the accelerometer Z has passed the self test.\n"
"bool accel_z\n"
"\n"
"# True if magnetometer is not saturated\n"
"bool mags_in_range\n"
"\n"
"# True if accelerometer is not saturated\n"
"bool accels_in_range\n"
"\n"
"# True if magnetometer seems to be calibrated\n"
"bool calibration\n"
;
  }

  static const char* value(const ::sbg_driver::SbgMag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sbg_driver::SbgMag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_stamp);
      stream.next(m.mag);
      stream.next(m.accel);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SbgMag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sbg_driver::SbgMag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sbg_driver::SbgMag_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_stamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "mag: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.mag);
    s << indent << "accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accel);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::sbg_driver::SbgMagStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SBG_DRIVER_MESSAGE_SBGMAG_H
